### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined with performance enabled

### ISSUE THREAD

**Issue by thelitek** [opbeat/opbeat-js#28] opened 2015-12-23 16:50 UTC
Given simple directive:
```` javascript
var DirectiveController;

DirectiveController = (function() {
    DirectiveController.$inject = ['$attrs' ];

    function DirectiveController( _attrs ) {
        this._attrs = _attrs;
        this._attrs.$observe('testDirective', this._initialize.bind(this));
    }

    DirectiveController.prototype._initialize = function( attrValue ) {
        console.log( 'YEY initialized with attr: ', attrValue )
    };

    return DirectiveController;

})();

angular.module('todomvc').directive('testDirective', function() {
    return {
        restrict: 'A',
        controller: DirectiveController,
        controllerAs: 'directiveCtrl',
        scope: true
    };
});
````
The app (for example todoMvc from this repo) works fine until I set `performance.enabled: true`. Then I receive the following error: 
````
TypeError: Cannot read property 'bind' of undefined
    at opbeatFunctionWrapper.DirectiveController (http://localhost:7000/angular/js/directives/testDirective.js:8:63)
    at new opbeatFunctionWrapper (eval at _buildWrapperFunction (http://localhost:7000/angular-opbeat.js:3494:11), <anonymous>:19:38)
````
which points to a line:
```` javascript
var F = new Function('ctx', newBody.join('\n')) // eslint-disable-line no-new-func
````

**Comment by auchenberg** [comment] 2015-12-23 17:55
Thanks for the report @thelitek! This is most likely caused by us not setting the correct prototype on wrapped objects.

I'll have a look.

**Comment by auchenberg** [comment] 2015-12-30 19:29
@thelitek I just pushed a fix for this. This will go out in next release.

**Closed** 2015-12-30 19:29 UTC
Labels: bug
